### ISSUE TITLE
Alignment with arrayvec

### ISSUE THREAD

**Issue by burdges** [auxoncorp/fixed-slice-vec#7]
I'm curious what you found that prevents the arrayvec crate itself from being modified to support both array and slices?  I suppose the compiler might fail to propagate the constant length somewhere, causing a performance regression relative to arrayvec?

**Comment by ZackPierce** [comment]
`arrayvec` is pretty firmly built around the notion of knowing the capacity of the backing array at compile time, as a constant.  It's built into the generic [Array trait](https://docs.rs/arrayvec/0.5.1/arrayvec/trait.Array.html) parameter required by an `ArrayVec` instance. That requirement is at odds with slice-based capacity, since slices do not encode their lengths into their type signature for use at compile time.

Perhaps after numeric const type parameters stabilize it will be possible to construct an ArrayVec (or similar) out of a slice and an associated constant size, at the cost of some initial checks. I suppose we'll have to see.

**Comment by burdges** [comment]
There are also differences in how the different arrayvec-like crates handle `MaybeUninit`.  In particular `MaybeUninit<&'s [u8]>` might not work too well.  Just curious, thanks!
